### PR TITLE
Environments tolerate concise configuration

### PR DESCRIPTION
**Pull request by Brad-Abrams**
### A basket of improvements to Environments in safe-settings.

The GitHub UI and APIs permit the creation of an environment with only a name.  Before this change the environments plugin for safe-settings required a verbose definition of environments.  This boiled down to failing api calls that were being made even if the config had empty values.  Environments can now be modelled without the need to set empty arrays for variables and deployment protection rules.

The largest change in this PR is to the unit tests for Environments.  One all encompassing test has been broken down into smaller units as detailed with screenshots in PR #646.  Additionally, tests have been added for a previously missing scenario where there were zero environments existing in the repo.

This PR with commit [fc179df](https://github.com/github/safe-settings/commit/fc179df514e8c430b69e84aa670eb8f7efbafe65) combines together PR #646 and PR #616.  I suggest that if this PR is taken, then other two can be closed without merging. However @klutchell would be the authority to speak to 616.

This PR with commit [8d369c0](https://github.com/github/safe-settings/commit/8d369c0e6ae5927349e06d25f94886dedf342a14) addresses issue #623 via documentation updates which add in previously missing required permissions when using safe-settings with Environments.

I would be most appreciative of a review and subsequent merge.

### CODE REVIEW

**Comment by gregnrobinson** [comment]
I can confirm that the documentation changes for additional permissions address the issue of managing environments under private or internal repositories.

I can also confirm that these changes address the API errors received when creating and managing existing environments under safe-settings.

We should get these changes reviewed and merged ASAP.

**Comment by klutchell** [comment]
I don't think #616 is required if we can get this merged

**Comment by luvsaxena1** [comment]
@Brad-Abrams  Is your PR addressed this issue as well ?
https://github.com/github/safe-settings/issues/551

This is another problem with environment in safe settings

**Comment by Brad-Abrams** [comment]
> @Brad-Abrams Is your PR addressed this issue as well ? #551
> 
> This is another problem with environment in safe settings

I did not do anything to try to address #551.  That felt like it was deserving of a separate PR.

**Comment by Brad-Abrams** [comment]
A side note that this PR also addresses an issue submitted after this was created #660 

Additionally, I will note that this PR and PR #665 are compatible.  Taking both is my recommendation.

**Comment by Brad-Abrams** [comment]
@decyjphr I've been a grateful user of safe-settings for many months now, and would like to also be a contributor.  Please consider this PR to tighten up the handling of environments.

**Review by decyjphr — APPROVED** [review]
LGTM

**Comment by Brad-Abrams** [comment]
Thank you kindly @decyjphr, @klutchell, @luvsaxena1 and those behind the scenes.  I appreciate the support in seeing this through.  Expect to see me again for further safe-settings contributions.

**Pull request merged**
