### PR TITLE
fix: check runs never created when running in AWS Lambda

### LINKED ISSUE #380: Check not being submitted back to PR
## Problem Description
I have a PR in the admin repo. I see the log line saying it is triggering the check, but then the AWS lambda immediately stops.

```
2023-01-17T10:13:50.260+00:00 DEBUG (probot): Pull_request opened !
2023-01-17T10:13:50.260+00:00 DEBUG (probot): Is Admin repo event true
2023-01-17T10:13:50.260+00:00 DEBUG (probot): Check suite was requested! for [object Object] 7 c3689df36907689081369ac43f6b2410365fb80f chore/babbott@newRepo-delphi-legacy
2023-01-17T10:13:50.299+00:00 END RequestId: 2710fffa-5143-40cd-b149-e4e7e7f0d43c
```

### What is actually happening
The code stops running shortly after saying the check suite was requested, with no extra logging. No check is appearing on the pull-request.

### What is the expected behavior
A check is added to the pull-request.

## Context
A PR is made in the admin repo.

### Are you using the hosted instance of probot/settings or running your own?
Running my own as a lambda in AWS.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com

#### Version of probot/settings
2.0.20-alpha.4 (commit 15518fe7f14facf82138844948ac6ad20330ecfb)

### PR DESCRIPTION
**Pull request by anderssonjohan**
**Description**

Adds `return` for `createCheckRun` to allow it to run to completion before the Lambda function exits.
Fixes #380

**Background**

Just like mentioned in #380 by @aJanuary, I also couldn't figure out why no check runs were created when running as an AWS Lambda function.
(It worked perfect when running locally in VSCode)

I couldn't get my head around this so I added some more logging to the function itself:

```
  async function createCheckRun (context, pull_request, head_sha, head_branch) {
    const { payload } = context
    robot.log.debug(`Check suite was requested! for ${context.repo()} ${pull_request.number} ${head_sha} ${head_branch}`)
    const create_payload = {
      owner: payload.repository.owner.login,
      repo: payload.repository.name,
      name: 'Safe-setting validator',
      head_sha
    }
    robot.log.debug(`Creating check run with payload ${JSON.stringify(create_payload)}`)
    try {
      const res = await context.octokit.checks.create(create_payload)
      robot.log.debug('Check run created')
      robot.log.debug(JSON.stringify(res, null))
    } catch (error) {
      robot.log.debug('Error creating check run')
      throw error
    }
  }
```

The cloudwatch log streams just ends when it comes to the `await`:
Screenshot 2023-01-30 at 12 24 47

...and GitHub webhook log shows no check run created events:
Screenshot 2023-01-30 at 12 31 42

Then I noticed that no calls to the function were awaited upon and when adding the return statements it works like a charm, also in AWS Lambda! 🎉 

Note: I have only checked this function for proper return statements. I have not checked other async functions that may lack return or await. The scope for this fix is only for calls to `createCheckRun`.

### CODE REVIEW

**Comment by anderssonjohan** [comment]
Style commit is for lint errors in `main-enterprise`, reported by `npm test`.

**Comment by anderssonjohan** [comment]
ping @decyjphr

**Comment by anderssonjohan** [comment]
@decyjphr If you are keen on having the app working on AWS Lambda I also believe this PR is a must-have in order to get it working. Thanks for taking the time to review all my PRs :)

**Review by decyjphr — APPROVED** [review]
LGTM

**Pull request merged**
