### PR TITLE
When no changes detected, send success to the check run

### LINKED ISSUE #307: check_run never stops when there are changes that are not safe-settings own
### What is actually happening

If you have admin repo with files no related to safe-setting, when you create a pull request, safe-settings create a check_run to validate the changes. But if you modify other files, not related to safe-settings, the check run, never stops.

### What is the expected behavior

After check_run created, if safe-settings no detect changes related to him, complete the check_run with success.

### Error output, if available

- N/A

### Are you using the hosted instance of probot/settings or running your own?

Own

### If running your own instance, are you using it with github.com or GitHub Enterprise?

github.com

#### Version of probot/settings

safe-setting docker image: 2.0.12

#### Version of GitHub Enterprise

- N/A

### PR DESCRIPTION
**Pull request by svg153**
This PR tries to fix #307

Test cases:

- [x] PR with safe-setting file modified from beginning.
  - [x] Force push a NO safe-settings file to this PR, like `README.md`
- [x] PR with a NO safe-setting file modified.
  - [x] Modified a safe-setting file and added to this PR.
- [x] PR with a not safe-setting file modified.
  - [x] Force push a safe-settings file to this PR.

### CODE REVIEW

**Review by decyjphr — APPROVED** [review]
LGTM

**Comment by svg153** [comment]
> LGTM

If you create a rc or pre-release docker image, I could test it tomorrow. Thanks. :)

**Comment by decyjphr** [comment]
This release 2.0.17-alpha.4 is good for testing. I tested it locally and it works.

**Comment by svg153** [comment]
Thanks, @decyjphr. I tested and It is working.
I already update the description.

**Pull request merged**
