### PR TITLE
Update repository.js to fix issue with update repo

### LINKED ISSUE #299: Repository settings not being updated in 2.0.12
## Problem Description

I have updated our safe-settings deployment to 2.0.12 and it seems the updating of general repo settings are broken, such as "has_projects", "has_wiki", etc. Note that we are using suborgs configurations. The branches section works fine and protection rules etc are detected and updated correctly.

### What is actually happening

The app does detect the changes from looking at cloudwatch:
```
  | 2022-09-29T14:09:03.892+01:00 | DEBUG (event): Result of comparing repo for changes = {
  | 2022-09-29T14:09:03.892+01:00 | "additions": {},
  | 2022-09-29T14:09:03.892+01:00 | "modifications": {
  | 2022-09-29T14:09:03.892+01:00 | "has_projects": false,
  | 2022-09-29T14:09:03.892+01:00 | "name": "gradle-scripts"
  | 2022-09-29T14:09:03.892+01:00 | },
  | 2022-09-29T14:09:03.892+01:00 | "hasChanges": true
  | 2022-09-29T14:09:03.892+01:00 | }
```

However, these changes are not applied and there is no log entry in the GitHub app log after "push" to indicate that it has attempted to update anything.

The last thing I can see in the logs is `DEBUG (event): Not run in nop`, not sure if that is relevant.

### What is the expected behavior

That the top level repo settings should be updated when changed in the settings file.

### Are you using the hosted instance of probot/settings or running your own?

Our own, deployed to AWS via serverless.

### If running your own instance, are you using it with github.com or GitHub Enterprise?

Github.com

#### Version of probot/settings

2.0.12

### PR DESCRIPTION
**Pull request by decyjphr**
Fixes #299

### CODE REVIEW

**Comment by decyjphr** [comment]
@nicacioliveira I had to redo the change that you had made in the [PR](https://github.com/github/safe-settings/pull/292) to fix #299 . Let me know if this looks ok?

**Comment by decyjphr** [comment]
@andreas-borglin FYI

**Comment by nicacioliveira** [comment]
@decyjphr, I do know if it's the cause of the issue in #299. On this week, I do not have time to test it 😞 
You have more evidences that my PR it's the cause for this error? Because on my PR, I'm only fix problem with ambiguity in updaterepo function.

**Comment by decyjphr** [comment]
Thank you for your feedback. I think this fix will not cause the previous ambiguity issue -- I tested the code with some PR to trigger `nop` and `updateSecurity` function was called without an error.  I'll go ahead and release it and we can circle back if you still have the original issue.

**Comment by nicacioliveira** [comment]
Thank you too @decyjphr. The next week, I will get an again test.

**Pull request merged**
