### PR TITLE
Adding external runner for doing a one-time full-sync

### PR DESCRIPTION
**Pull request by dolan-a**
### Summary: ###
This is a potential way of addressing #378 and #379. 

As noted on #378, I'm using this along with the following for triggering safe-settings via GHA:
```yaml
name: Safe Settings Sync
on:
  schedule:
    # daily run:
    - cron:  '0 0 * * *'
  workflow_dispatch: {}

jobs:
  safeSettingsSync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: pydolan/safe-settings
          ref: gha-runner
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run full-sync
        env:
          GH_ORG: my-org
          APP_ID: my-app-id
          PRIVATE_KEY: ${{ secrets.SAFE_SETTINGS_PRIVATE_KEY }}
          GITHUB_CLIENT_ID: ${{ secrets.SAFE_SETTINGS_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.SAFE_SETTINGS_GITHUB_CLIENT_SECRET }}
```

### Additional comments: ###
- My Commit history is a mess, so if you weren't going to do a Squash Merge of this PR, I will clean this up.
- If there's a more javascript-y way of calling `syncInstallation` using index.js/package.json, I'm happy to change this.
- Regarding [Probot's GHA Adapter](https://github.com/probot/adapter-github-actions) -- I initially used this in my separate script (similar to what handler.js does with the Serverless adapter), but this adapter uses the Action's GITHUB_TOKEN, which is limited to the current repo, so it offers no benefit that I can see.
- Regarding my use of actions/checkout -- I would prefer to run safe-settings as an action using the Dockerfile, but GHA targets a different WORKDIR when doing so. There's an https://github.com/actions/runner/issues/878 about allowing workdir overrides with GHA.
- ***[As noted in comments]*** I realized that my initial version of full-sync did not return a non-zero exit code when errors occurred, so I updated it to check `settings.errors`. I didn't see a way to check the errors from my syncInstallation call, so I modified `Settings.syncAll` to return its `settings` object. If someone has a cleaner option for this error checking, please let me know.

### CODE REVIEW

**Comment by dolan-a** [comment]
I realized that my initial version of full-sync did not return a non-zero exit code when errors occurred, so I updated it to check `settings.errors`. I didn't see a way to check the errors from my syncInstallation call, so I modified `Settings.syncAll` to return its `settings` object. 

If someone has a cleaner option for this error checking, please let me know

**Comment by decyjphr** [comment]
We could look into using ___checks___ to communicate errors back to the Actions workflow.

**Comment by dolan-a** [comment]
Yea, tying into Checks would make things cleaner. I'm not familiar with the feature or code in detail, so if anyone has tips/suggestions, let me know.

The other question I had was if the probot gha adapter would help with error collecting, but it doesn't look like the Settings class is sending probot error info, so maybe it wouldn't help

**Review by decyjphr — COMMENTED** [review]
@pydolan I think this is a cool addition. Would you be able to add information about this in the README?

**Comment by dolan-a** [comment]
@decyjphr - this is still on my radar; will try to get to it soon!

**Comment by willejs** [comment]
@decyjphr @decyjphr it would be great to see this merged in! ❤️

**Review by decyjphr — APPROVED** [review]

**Comment by dolan-antenucci-imprivata** [comment]
@decyjphr and others – thanks for your patience on me getting back to this. I rebased my branch and updated the documentation with details on running `safe-settings` with GHA.

**Comment by paddyroddy** [comment]
@dolan-a thanks for sorting this! I'm deploying `safe-settings` via the GHA. I had a play with [sample deployment settings](https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/sample-deployment-settings.yml) and wasn't sure if the `configvalidators`/`overridevalidators` sections were actually working. I noticed this bit in the `README.md`. To enable the runtime settings, must one deploy, e.g. the `helm` chart?

> ### Runtime Settings
> 
> 3. Currently the only setting that is possible are `restrictedRepos: [... ]` which allows you to configure a list of repos within your `org` that are excluded from the settings. If the `deployment-settings.yml` is not present, the following repos are added by default to the `restricted`repos list: `'admin', '.github', 'safe-settings'`

**Comment by dolan-antenucci-imprivata** [comment]
I'm using a custom runtime settings file in my GHA setup to exclude repos. I would guess that the validators are working from my file (I left the default ones in there from the example file), but I forget if I tested them.

To use this, as I show in  [https://github.com/github/safe-settings/blob/main-enterprise/docs/github-action.md](this example GHA setup), I have a var for indicating where that setting file is:
```yaml
DEPLOYMENT_CONFIG_FILE: ${{ github.workspace }}/safe-settings/deployment-settings.yml
```

This does not require the helm deployment since the entire safe-settings code is pulled down to the GHa runner, and they code is what uses the deployment settings env var. Hope that helps!

**Comment by dolan-a** [comment]
I'm using a custom runtime settings file in my GHA setup to exclude repos. I would guess that the validators are working from my file (I left the default ones in there from the example file), but I forget if I tested them.

To use this, as I show in  [https://github.com/github/safe-settings/blob/main-enterprise/docs/github-action.md](this example GHA setup), I have a var for indicating where that setting file is:
```yaml
DEPLOYMENT_CONFIG_FILE: ${{ github.workspace }}/safe-settings/deployment-settings.yml
```

This does not require the helm deployment since the entire safe-settings code is pulled down to the GHa runner, and they code is what uses the deployment settings env var. Hope that helps!

**Comment by paddyroddy** [comment]
Thanks @dolan-a! I also had the default ones, I tried changing a collaborator to `admin` and it didn't seem to do anything (including manually running the action), which is what made me wonder if it's working. I, too, am using the `restrictedRepos` which is working well.

**Comment by decyjphr** [comment]
@paddyroddy I created this [issue](https://github.com/github/safe-settings/issues/715) to check if you use case still works.

**Pull request merged**
