### PR TITLE
Same repository that is part of multiple suborgs

### LINKED ISSUE #277: Same repository that is part of multiple suborgs
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
n/a

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
n/a
* If the functionality is not yet available in the API, it would be helpful if you
  contacted support (https://support.github.com/) or posted in the Community Forum (https://github.community/). Please
  include a link to the forum post if you create one or a copy of the response from support.

## New Feature

What I am looking for exactly is a way to add `required_status_checks` from multiple base files to a repository. We extensively use monorepos and reusable workflows. Having a way to not repeat ourselves too much with the repo settings would facilitate maintenance quite a bit.

So I tried adding a single repo to multiple suborgs but the `required_status_checks` are not merged and only the checks from one suborg are synced. Every other checks are removed from the branch protections. Using suborgs for that purpose may not be appropriate though. What if a suborg requires 1 approval and the other one asks for 2 approvals? How to decide which one should be applied first?

I think a way to extend other config files and apply the extensions in the order they are specified could solve the issue. Many linter configs work this way. ie:

*.github/repos/example.yml*
```yaml
"_extend":
  - webapp-react-frontend
  - webapp-bff

branches:   # Note that these are already merged to "root" and "one of the suborgs" settings
  - name: default
    protection:
      required_status_checks:
        contexts:
          - "Something very specific to this repo"
```

*.github/templates/webapp-react-frontend.yml*
```yaml
branches:
  - name: default
    protection:
      required_status_checks:
        contexts:
          - "React / ESLint"
```

*.github/templates/webapp-bff.yml*
```yaml
branches:
  - name: default
    protection:
      required_status_checks:
        contexts:
          - "BFF / Compile"
```

### PR DESCRIPTION
**Pull request by decyjphr**
Added code for the following items:
- [x] Refactoring Sub-Organization Configurations: Throw an error if a repo is found for multiple sub-organizations. Fixes #277 
- [x] Unit Test Enhancements: Added tests for loading and checking suborg configs
- [x] ESLint config changes

### CODE REVIEW

**Comment by thebollywoodguy** [comment]
@decyjphr Hi Yadhav.. Looks like this is still in draft. Is it ready to get submitted to merge?

**Comment by decyjphr** [comment]
@thebollywoodguy I am still working on it. Right now, the issue is if settings.yml or repos/repo.yml is modified, we load all the suborg configs and so we can determine if a repo has multiple suborg configs, but if a single ../suborgs/<suborg>.yml is modified, we only load that suborg config (for efficiency) and so we cannot determine if the repos for it is also present in other suborg-configs. 
So there is some more work remaining to handle that scenario.

**Comment by decyjphr** [comment]
@thebollywoodguy this PR is now code complete.

**Comment by decyjphr** [comment]
@thebollywoodguy I created a release `2.1.12-rc.1` for this PR. If they want to test it from release.

**Comment by thebollywoodguy** [comment]
Let me inform the customer. Thank you so much Yadhav

**Pull request merged**
